mytweets/urls.py
from django.conf.urls import url

from .views import TweetListView


urlpatterns = [
    url(r"^$", TweetListView.as_view(), name="home"),
]

mytweets/models.py
import datetime

from django.db import models


def format_date(date_str):
    if date_str:
        return datetime.datetime.strptime(date_str, "%Y-%m-%d %H:%M:%S %z")


class Tweet(models.Model):
    tweet_id = models.IntegerField()
    in_reply_to_status_id = models.IntegerField(null=True, blank=True)
    in_reply_to_user_id = models.IntegerField(null=True, blank=True)
    timestamp = models.DateTimeField()
    source = models.TextField()
    text = models.TextField()
    retweeted_status_id = models.IntegerField(null=True, blank=True)
    retweeted_status_user_id = models.IntegerField(null=True, blank=True)
    retweeted_status_timestamp = models.DateTimeField(null=True, blank=True)
    expanded_urls = models.TextField(blank=True)

    @classmethod
    def import_archive(cls, csv_data):
        """
        Expects a DictReader (`csv_data`) from a Twitter archive.

        >>> import csv
        >>> from mytweets.models import Tweet
        >>> reader = csv.DictReader(open("../tweets.csv", "r"))
        >>> Tweet.import_archive(reader)
        """
        for tweet in reversed(list(csv_data)):
            cls.objects.create(
                tweet_id=tweet["tweet_id"],
                in_reply_to_status_id=tweet["in_reply_to_status_id"] or None,
                in_reply_to_user_id=tweet["in_reply_to_user_id"] or None,
                timestamp=format_date(tweet["timestamp"]),
                source=tweet["source"],
                text=tweet["text"],
                retweeted_status_id=tweet["retweeted_status_id"] or None,
                retweeted_status_user_id=tweet["retweeted_status_user_id"] or None,
                retweeted_status_timestamp=format_date(tweet["retweeted_status_timestamp"]),
                expanded_urls=tweet["expanded_urls"]
            )

mytweets/views.py
from django.views.generic import ListView

from pinax.types.periods import get_period

from .models import Tweet


class TweetListView(ListView):
    model = Tweet
    template_name = "homepage.html"
    paginate_by = 100
    ordering = "-pk"

    def get_queryset(self):
        queryset = super(TweetListView, self).get_queryset()
        period = self.request.GET.get("period")
        if period:
            queryset = queryset.filter(
                timestamp__range=get_period(period).get_start_end()
            )
        return queryset

mytweets/templates/_footer.html
{% load i18n %}

{% trans "&copy; 2016 &lt;your company here&gt;" %}

mytweets/templates/_scripts.html
<script src='/site_media/static/js/site-5e73bbeeb0.js'></script>

mytweets/templates/_styles.html
<link href='/site_media/static/css/site-9713c11499.css' rel='stylesheet' />

mytweets/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}pinax-project-zero{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <form class="form-inline pull-right"><div class="form-group"><input class="form-control input-sm" name="period" value="{{ request.GET.period }}" placeholder="Enter a period format..." /></div></form>
            <span class="pull-right" style="padding-right: 15px;">
                <a class="btn btn-sm btn-default" href="?period=Q-2014-3">Q3 2014</a>
                <a class="btn btn-sm btn-default" href="?period=W-2013-04">4th Week of 2013</a>
                <a class="btn btn-sm btn-default" href="?period=M-2015-07">July 2015</a>
            </span>
            <h3 class="panel-title" style="font-size: 26px;">My Tweets</h3>
        </div>
        <table class="table table-striped table-condensed">
            <thead><tr><th>Date</th><th>Tweet</th></tr></thead>
            <tbody>{% for tweet in tweet_list %}<tr><td nowrap>{{ tweet.timestamp }}</td><td>{{ tweet.text }}</td></tr>{% endfor %}</tbody>
        </table>
    </div>
    {% include "pagination/pagination.html" %}
{% endblock %}

mytweets/templates/site_base.html
{% extends "theme_bootstrap/base.html" %}

{% load staticfiles %}
{% load i18n %}


{# remove to bring back topbar #}
{% block topbar_base %}{% endblock %}


{% block styles %}
    {% include "_styles.html" %}
{% endblock %}


{% block extra_head_base %}
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}


{% block scripts %}
    {% include "_scripts.html" %}
{% endblock %}

{% block extra_body_base %}
    {% block extra_body %}{% endblock %}
{% endblock %}